#!/bin/sh
dir=`dirname "$0"`
dir=`cd "$dir"; pwd`
if test "$MRI_RUBY" != ""; then
	exec $MRI_RUBY "$dir/echo_server.rb" "$@"
else
	echo 'In order to run echo_server, you must set the environment variable $MRI_RUBY.' >&2
	exit 1
fi
