name: CI

on:
  push:
    branches:
      - "*"
  pull_request_target:
    types:
      - assigned
      - synchronize

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        ruby-version:
          - "3.1"
          - "3.4"
          - jruby
      fail-fast: false
    env:
      BUNDLE_WITHOUT: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run RSpec tests
        run: /usr/bin/timeout -s QUIT 120 bundle exec rake test
        timeout-minutes: 3
        env:
          MRI_RUBY: "env RUBYOPT= RUBYLIB= /usr/bin/ruby"

  lint-and-build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true

      - name: Check code formatting with Standard Ruby
        run: bundle exec standardrb

      - name: Build gem
        run: gem build daemon_controller.gemspec
